import { Task } from '@/components/tests-card'

export const tasks: Task[] = [
  {
    id: "1",
    date: "19/07/2025",
    description: "SEQ Extra - Simulado UERJ",
    status: "completed",
    details: {
      type: "Simulado UERJ",
      stage: "Simulados",
      evaluation: "UERJ Extra",
      score: ((32 / 60) * 10).toFixed(1),
      correct: 32,
      maxScore: 60,
      performance: ((32 / 60) * 100).toFixed(0) + "%",
    },
  },
  {
    id: "2",
    date: "17/07/2025",
    description: "2CH SE5.2 - Simulado Enem",
    status: "pending",
  },
  {
    id: "3",
    date: "16/07/2025",
    description: "2CH SE5.1 - Simulado Enem",
    status: "pending",
  },
  {
    id: "4",
    date: "14/07/2025",
    description: "pH20",
    status: "completed",
    details: {
      type: "Simulado Enem",
      stage: "Simulados",
      evaluation: "pH20",
      score: (3 / 5) * 10,
      correct: 3,
      maxScore: 5,
      performance: "80%",
    },
  },
  {
    id: "5",
    date: "14/07/2025",
    description: "pH21 - Redação em Sala",
    status: "pending",
  },
  {
    id: "6",
    date: "12/07/2025",
    description: "SE5.2 - Simulado Enem",
    status: "completed",
    details: {
      type: "Simulado Enem",
      stage: "Simulados",
      evaluation: "SE5.2",
      score: 45,
      correct: 45,
      maxScore: 60,
      performance: "100%",
    },
  },
  {
    id: "7",
    date: "10/07/2025",
    description: "2CH SE4.2 - Simulado Enem (Extra)",
    status: "pending",
  },
  {
    id: "8",
    date: "09/07/2025",
    description: "2CH SE4.1 - Simulado Enem (Extra)",
    status: "pending",
  },
  {
    id: "9",
    date: "08/07/2025",
    description: "pH19",
    status: "completed",
    details: {
      type: "Simulado Enem",
      stage: "Simulados",
      evaluation: "pH19",
      score: 45,
      correct: 45,
      maxScore: 60,
      performance: "84%",
    },
  },
  {
    id: "10",
    date: "07/07/2025",
    description: "pH20 - Redação em Sala",
    status: "completed",
    details: {
      type: "Redação",
      stage: "Redações",
      evaluation: "pH20 - Redação",
      score: 850,
      correct: 1000,
      maxScore: 1000,
      performance: "85%",
    },
  },
]